// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using react_template_data.Data;

namespace react_template_data.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20201103144632_FeedIdentityResourceTable")]
    partial class FeedIdentityResourceTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("react_template_data.Data.Master.BackgroundJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("react_template_data.Data.Master.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LicenceNo")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LicenceSince")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2020, 11, 3, 14, 46, 32, 446, DateTimeKind.Utc).AddTicks(4283));

                    b.Property<DateTime?>("LicenceTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("LicenceNo")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Database = "react-template-owner-dev",
                            LicenceNo = "default",
                            LicenceSince = new DateTime(2020, 11, 3, 14, 46, 32, 456, DateTimeKind.Utc).AddTicks(1819),
                            Name = "default"
                        });
                });

            modelBuilder.Entity("react_template_data.Data.Master.DomainSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("DomainSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Identifier = "react-template",
                            Name = "Front office",
                            Secret = "sD3fPKLnFKZUjnSV4qA/XoJOqsmDfNfxWcZ7kPtLc0I="
                        });
                });

            modelBuilder.Entity("react_template_data.Data.Master.GrantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("DomainSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("DomainSystemId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GrantTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            DomainSystemId = 1,
                            Name = "authorization_code"
                        });
                });

            modelBuilder.Entity("react_template_data.Data.Master.IdentityResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("DomainSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("DomainSystemId");

                    b.HasIndex("Name", "Claim")
                        .IsUnique();

                    b.ToTable("IdentityResources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Claim = "sub",
                            DomainSystemId = 1,
                            Name = "openid"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Claim = "email",
                            DomainSystemId = 1,
                            Name = "email"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Claim = "email_verified",
                            DomainSystemId = 1,
                            Name = "email"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Claim = "name",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Claim = "family_name",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Claim = "given_name",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Claim = "middle_name",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Claim = "nickname",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Claim = "preferred_username",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Claim = "profile",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Claim = "picture",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Claim = "website",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            Claim = "gender",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            Claim = "birthdate",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            Claim = "zoneinfo",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            Claim = "locale",
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            Claim = "updated_at",
                            DomainSystemId = 1,
                            Name = "profile"
                        });
                });

            modelBuilder.Entity("react_template_data.Data.Master.RedirectUri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("DomainSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("DomainSystemId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("RedirectUris");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            DomainSystemId = 1,
                            Uri = "https://localhost:44394"
                        });
                });

            modelBuilder.Entity("react_template_data.Data.Master.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ApiScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("DomainSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("DomainSystemId");

                    b.HasIndex("Name", "DomainSystemId", "ApiScope")
                        .IsUnique();

                    b.ToTable("Scopes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            ApiScope = false,
                            DomainSystemId = 1,
                            Name = "openid"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            ApiScope = false,
                            DomainSystemId = 1,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            ApiScope = false,
                            DomainSystemId = 1,
                            Name = "custom"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            ApiScope = true,
                            DomainSystemId = 1,
                            Name = "custom"
                        });
                });

            modelBuilder.Entity("react_template_data.Data.Master.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Default")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Dict")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Dict", "File")
                        .IsUnique();

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Default = true,
                            Dict = "default",
                            File = "bundle.css"
                        });
                });

            modelBuilder.Entity("react_template_data.Data.Master.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StyleId");

                    b.HasIndex("ClientId", "StyleId", "Path")
                        .IsUnique();

                    b.ToTable("Urls");
                });

            modelBuilder.Entity("react_template_data.Data.Master.BackgroundJob", b =>
                {
                    b.HasOne("react_template_data.Data.Master.Client", "Client")
                        .WithMany("BackgroundJobs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("react_template_data.Data.Master.GrantType", b =>
                {
                    b.HasOne("react_template_data.Data.Master.DomainSystem", "DomainSystem")
                        .WithMany("GrantTypes")
                        .HasForeignKey("DomainSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("react_template_data.Data.Master.IdentityResource", b =>
                {
                    b.HasOne("react_template_data.Data.Master.DomainSystem", "DomainSystem")
                        .WithMany("IdentityResources")
                        .HasForeignKey("DomainSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("react_template_data.Data.Master.RedirectUri", b =>
                {
                    b.HasOne("react_template_data.Data.Master.DomainSystem", "DomainSystem")
                        .WithMany("RedirectUris")
                        .HasForeignKey("DomainSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("react_template_data.Data.Master.Scope", b =>
                {
                    b.HasOne("react_template_data.Data.Master.DomainSystem", "DomainSystem")
                        .WithMany("Scopes")
                        .HasForeignKey("DomainSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("react_template_data.Data.Master.Url", b =>
                {
                    b.HasOne("react_template_data.Data.Master.Client", "Client")
                        .WithMany("Urls")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("react_template_data.Data.Master.Style", "Style")
                        .WithMany("Urls")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
